-- CREATE DATABASE IF NOT EXISTS `abc12366_gateway` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE `abc12366_gateway`;

DROP TABLE IF EXISTS log;
DROP TABLE IF EXISTS app;
DROP TABLE IF EXISTS api;
DROP TABLE IF EXISTS blacklist;

CREATE TABLE log(
  id VARCHAR(64) NOT NULL COMMENT '主键ID',
  uri VARCHAR(255) COMMENT '访问URI',
  userAgent VARCHAR(255) COMMENT '用户代理',
  ip VARCHAR(32) COMMENT 'IP地址',
  startTime BIGINT COMMENT '访问开始时间',
  endTime BIGINT COMMENT '访问结束时间',
  status INT COMMENT '结果状态',
  appId VARCHAR(64) COMMENT '访问AppId'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '访问日志表';

CREATE TABLE app(
  id VARCHAR(64) PRIMARY KEY NOT NULL COMMENT 'ID',
  name VARCHAR(32) NOT NULL COMMENT '应用名称',
  password VARCHAR(64) NOT NULL COMMENT '密码',
  mark VARCHAR(2048) COMMENT '描述',
  status BOOLEAN NOT NULL COMMENT '应用状态',
  createDate DATETIME COMMENT '创建时间',
  modifyDate DATETIME COMMENT '修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '应用信息表';

create table api(
  id VARCHAR(64) PRIMARY KEY NOT NULL COMMENT 'ID',
  name varchar(64) NOT NULL COMMENT 'API名称',
  mark VARCHAR(255) COMMENT '描述',
  method VARCHAR(64) COMMENT '访问方法:GET,POST,PUT,DELETE,ALL',
  role VARCHAR(64) COMMENT '角色',
  version VARCHAR(3) COMMENT '版本',
  appId VARCHAR(64) NOT NULL COMMENT 'AppId',
  status BOOLEAN NOT NULL COMMENT '接口状态',
  createDate DATETIME COMMENT '创建时间',
  modifyDate DATETIME COMMENT '修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '接口信息表';

create table blacklist(
  id VARCHAR(64) PRIMARY KEY NOT NULL COMMENT 'ID',
  ip varchar(32) NOT NULL COMMENT 'IP',
  mark VARCHAR(255) COMMENT '描述',
  status BOOLEAN NOT NULL COMMENT '状态',
  createDate DATETIME COMMENT '创建时间',
  modifyDate DATETIME COMMENT '修改时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT '黑名单信息表';